### PR TITLE
modify user-page and add fetchAboutMe() to show about me

### PR DESCRIPTION
**Pull request by nanda-thant-sin**
Modify user page to show about me section. And If a user is viewing his own page, there will be form to add his information and the `about me` message. Otherwise, user will see only `about me` message.

To Test,
Log in with your account. Then, go to `Your Page`. You will see both "This is `your email`'s about me." and form to add. Submitting the form will not work for now because I haven't add anything yet.

 Click [the link](http://su19-codeu-35-6225.appspot.com/user-page.html?user=abc) or change email in the link to something else. Then, you will not see the form anymore because you are not that user.

I am terrible at explaining things 🤣

### CODE REVIEW

**Comment by LiMengyang990726** [comment]
Hi Nanda! I just tested your page and I am not prompt to any log in with email yet.
The default user name is believed to be `abc` as I am not logged in yet and received the `About me` page of user `abc`

**Comment by nanda-thant-sin** [comment]
> Hi Nanda! I just tested your page and I am not prompt to any log in with email yet.
> The default user name is believed to be `abc` as I am not logged in yet and received the `About me` page of user `abc`

I think you means the link from my message. It is user page. It will show `about me` and `messages`. But you can't edit because you are not `abc`

**Comment by LiMengyang990726** [comment]
Hi Nanda! Thank you for doing this.

It's great that so far I think everything is working fine on my side. While I suggest others to test from this [link](http://su19-codeu-35-6225.appspot.com), then go to `Log in`.

**Comment by nanda-thant-sin** [comment]
> Hi Nanda! Thank you for doing this.
> 
> It's great that so far I think everything is working fine on my side. While I suggest others to test from this [link](http://su19-codeu-35-6225.appspot.com), then go to `Log in`.

Thank. That is why I said I am bad in explaining. 😂

**Pull request merged**
